baseURL = 'https://n00bady.xyz'
languageCode = 'en-us'
title = "n00bady's site"
theme = 'ficurinia'

# Change the copyrights at the footer
copyright = "n00bady - except those that aren't."

paginate = 5 # number of articles per page in the index page
summaryLength = 70 # How many words article summaries will have

[params]
author = "n00bady"
description = "My personal site"  # this will be added as metadata

posts = "ramblings" # content directory where to find home page posts; default searches in "posts" and "post"
showPostsLink = true # show or hide the link to the simple post list
extraContentDirs = ["about"] # other content directories to render similarly to the homepage
showcaseDir = "showcase" # create a content directory that shows a special showcase section in the homepage

# shows a specified single page as a home page, instead of the tranditional articles list
# requires setting homeSinglePage
# goes well with extraContentDirs
showSinglePageAsHome = true
homeSinglePage = "/home"

# It's best to put these icons in the static folder of your site
logo = "/logo.svg"
favicon = "/favicon.png" # 32x32
faviconIco = "/favicon.ico" # 32x32
svgicon = "/logo.svg"
icon512 = "/icon512.png"

logoRightOfTitle = false # positions the logo to the right of the title; default: false

showTags = false # show the Tags menu item; default: true
showRss = true # show the link for the RSS feed; default true

imageInArticlePreview = false # show images in article preview; default: false
fitImageInArticlePreview = false # make article preview images fit the article preview instead of getting cropped
articleSummary = true # show a summary in article preview; default: true

fontFamily = "JetBrains Mono" # changes the font, default: "JetBrains Mono"
titleFontFamily = "JetBrains Mono" # font used for titles and headings
monospaceFontFamily = "JetBrains Mono" # changes the monospace font for code

# multipliers applied to font sizes, useful for custom fonts that may be too big or too small
titleFonSizeMultiplier = 1.0
mainFontSizeMultiplier = 1.0
monoFontSizeMultiplier = 1.0

contentWidth = "900px" # max width of the site content, css syntax

paperCards = false # enable paper card style; default false
buttonTags = false # enable button tag style; default false
tagsInArticlePreview = false # enable tags list in the article preview card
gridView = false # show post list as a grid. goes well with paper card
bigArticleTitle = false # make the title in the single article view bigger
navtype = "standard" # changes the style of the pagination, available styles are: "standard", "circles"
enableShadow = false # shows a shadow around some elements
menuStyle = "standard" # changes the style of the main site navigation menu, available styles are: "standard", "buttons"

enableSearch = false # enable search page; default: true
searchbarEverywhere = false # if the searchbar should be shown in every page; requires enableSearch; default: true
searchMenuLink = false # add a search link to the navigation menu; requires enableSearch
mobileHamburgerNav = true # alternative hamburger menu layout for the main nav menu when screen is small

enableFeatured = false # enable a particular view for articles marked as featured (featured: true in the article frontmatter)

underlineTitleLinks = true # show an underline also for links that are titles; default: false

# enable comments support with commento using the script from your server
# commento = "https://example.con/js/commento.js"

# enable comments support with cactus comments (cactus.chat)
# cactusCommentsSiteName = "example.com"
# cactusCommentsServerName = "cactus.chat"
# cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"

# enable analytics using Plausible
# plausibleScriptUrl = "https://something.com/...."
# plausibleDomain = "example.com"

# enable analytics using Umami
# umamiScriptUrl = "https://something.com/...."
# umamiWebSiteId = "example-tracking-code"

enableShareOnFediverse = false # enable a button at the end of an article to share it on the fediverse
tocBeforeImage = false # show the table of contents before the main article image; default: false

# You can customize all the colors in this theme
# Colors are defined in data/colors.yml

# alternative sidebar layout
enableSidebarLayout = false
tocInSidebar = false # if the sidebar is enabled, show the TOC in the sidebar


# redirect to baseURL if current URL host doesn't match
# useful if deploying in gitlab pages with custom domain and don't want
# the username.gitlab.io/website url to persist
# this requires you to set baseURL (see above)
forceRedirect = false

infiniteScrolling = false # activates infinite scrolling instead of regular pagination
enableFooterColums = false # activates footer columns, as described below
enableJumbotron = false # enables jumbotron, as described below
# related articles will be selected randomly based on tags and show at 
# the bottom of the article, after the comments
enableRelatedArticles = false
relatedArticlesNum = 2 # how many related articles to show
randomRelated = false # sorts related articles in random order (randomized at build time)

[menu]
# These links will be added to the main navigation menu, sorted by weight
# other elements in this menu are added automatically from the "pages" folder
# the folder it will look into can be customized with the pages variable
# in params above
  [[menu.icons]]
  identifier = "gitlab"
  name = "gitlab"
  url = "https://gitlab.com/n00bady"
  weight = 10
  [[menu.icons]]
  identifier = "email"
  name = "kaz00@vivaldi.net"
  url = "mailto:kaz00@vivaldi.net"
# These links (menu.icons) will be added as icon links below the main nav
  # [[menu.icons]]
  # identifier = "gitlab"
  # name = "GitLab"
  # url = "https://gitlab.com/gabmus"
  # weight = 10
  # [[menu.icons]]
  # identifier = "gnome"
  # name = "GNOME GitLab"
  # url = "https://gitlab.gnome.org/gabmus"
  # weight = 20

# this section is necessary if you want infinite scrolling
# it allows to output the article list as paged JSON so that "pages" can be retrieved via javascript
# [outputs]
# home = ["HTML", "JSON"]

